server:
  port: 8090
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  profiles:
    active:
    - dev
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
        
  jackson:
    serialization:
      fail-on-empty-beans: false
      
---
spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rokacheck?serverTimezone=Asia/Seoul
    username: check
    password: 1234

---
spring:
  profiles: dev
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:check
    generate-unique-name: false
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none